version: '3.9'

services:
  gewechat:
    image: registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine # 拉取镜像
    container_name: gewechat
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - ./temp:/root/temp
    restart: always
