import {Configuration} from '../entity/Configuration'

export class EmojiConverter {
    public static emojiUrl = 'https://raw.githubusercontent.com/finalpi/wechat-emoji/main/'
    public emojiMapping: Record<string, string> = {
        '[微笑]': `<a href="${EmojiConverter.emojiUrl}%E5%BE%AE%E7%AC%91.png">[微笑]</a>`,
        '[撇嘴]': `<a href="${EmojiConverter.emojiUrl}%E6%92%87%E5%98%B4.png">[撇嘴]</a>`,
        '[色]': '😍',
        '[发呆]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E5%91%86.png">[发呆]</a>`,
        '[得意]': '😎',
        '[流泪]': '😭',
        '[害羞]': `<a href="${EmojiConverter.emojiUrl}%E5%AE%B3%E7%BE%9E.png">[害羞]</a>`,
        '[闭嘴]': `<a href="${EmojiConverter.emojiUrl}%E9%97%AD%E5%98%B4.png">[闭嘴]</a>`,
        '[睡]': '😴',
        '[大哭]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%A7%E5%93%AD.png">[大哭]</a>`,
        '[尴尬]': `<a href="${EmojiConverter.emojiUrl}%E5%B0%B4%E5%B0%AC.png">[尴尬]</a>`,
        '[发怒]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E6%80%92.png">[发怒]</a>`,
        '[调皮]': '😜',
        '[呲牙]': `<a href="${EmojiConverter.emojiUrl}%E5%91%B2%E7%89%99.png">[呲牙]</a>`,
        '[惊讶]': `<a href="${EmojiConverter.emojiUrl}%E6%83%8A%E8%AE%B6.png">[惊讶]</a>`,
        '[难过]': `<a href="${EmojiConverter.emojiUrl}%E9%9A%BE%E8%BF%87.png">[难过]</a>`,
        '[囧]': `<a href="${EmojiConverter.emojiUrl}%E5%9B%A7.png">[囧]</a>`,
        '[抓狂]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%93%E7%8B%82.png">[抓狂]</a>`,
        '[吐]': '🤮',
        '[偷笑]': `<a href="${EmojiConverter.emojiUrl}%E5%81%B7%E7%AC%91.png">[偷笑]</a>`,
        '[愉快]': `<a href="${EmojiConverter.emojiUrl}%E6%84%89%E5%BF%AB.png">[愉快]</a>`,
        '[白眼]': '🙄',
        '[傲慢]': `<a href="${EmojiConverter.emojiUrl}%E5%82%B2%E6%85%A2.png">[傲慢]</a>`,
        '[困]': '🥱',
        '[惊恐]': `<a href="${EmojiConverter.emojiUrl}%E6%83%8A%E6%81%90.png">[惊恐]</a>`,
        '[憨笑]': `<a href="${EmojiConverter.emojiUrl}%E6%86%A8%E7%AC%91.png">[憨笑]</a>`,
        '[悠闲]': `<a href="${EmojiConverter.emojiUrl}%E6%82%A0%E9%97%B2.png">[悠闲]</a>`,
        '[咒骂]': `<a href="${EmojiConverter.emojiUrl}%E5%92%92%E9%AA%82.png">[咒骂]</a>`,
        '[疑问]': `<a href="${EmojiConverter.emojiUrl}%E7%96%91%E9%97%AE.png">[疑问]</a>`,
        '[嘘]': `<a href="${EmojiConverter.emojiUrl}%E5%98%98.png">[嘘]</a>`,
        '[晕]': '😵',
        '[衰]': `<a href="${EmojiConverter.emojiUrl}%E8%A1%B0.png">[衰]</a>`,
        '[骷髅]': '💀',
        '[敲打]': `<a href="${EmojiConverter.emojiUrl}%E6%95%B2%E6%89%93.png">[敲打]</a>`,
        '[再见]': `<a href="${EmojiConverter.emojiUrl}%E5%86%8D%E8%A7%81.png">[再见]</a>`,
        '[擦汗]': `<a href="${EmojiConverter.emojiUrl}%E6%93%A6%E6%B1%97.png">[擦汗]</a>`,
        '[抠鼻]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%A0%E9%BC%BB.png">[抠鼻]</a>`,
        '[鼓掌]': `<a href="${EmojiConverter.emojiUrl}%E9%BC%93%E6%8E%8C.png">[鼓掌]</a>`,
        '[坏笑]': `<a href="${EmojiConverter.emojiUrl}%E5%9D%8F%E7%AC%91.png">[坏笑]</a>`,
        '[右哼哼]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%B3%E5%93%BC%E5%93%BC.png">[右哼哼]</a>`,
        '[鄙视]': `<a href="${EmojiConverter.emojiUrl}%E9%84%99%E8%A7%86.png">[鄙视]</a>`,
        '[委屈]': `<a href="${EmojiConverter.emojiUrl}%E5%A7%94%E5%B1%88.png">[委屈]</a>`,
        '[快哭了]': `<a href="${EmojiConverter.emojiUrl}%E5%BF%AB%E5%93%AD%E4%BA%86.png">[快哭了]</a>`,
        '[阴险]': `<a href="${EmojiConverter.emojiUrl}%E9%98%B4%E9%99%A9.png">[阴险]</a>`,
        '[亲亲]': `<a href="${EmojiConverter.emojiUrl}%E4%BA%B2%E4%BA%B2.png">[亲亲]</a>`,
        '[可怜]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%AF%E6%80%9C.png">[可怜]</a>`,
        '[笑脸]': `<a href="${EmojiConverter.emojiUrl}%E7%AC%91%E8%84%B8.png">[笑脸]</a>`,
        '[生病]': `<a href="${EmojiConverter.emojiUrl}%E7%94%9F%E7%97%85.png">[生病]</a>`,
        '[脸红]': `<a href="${EmojiConverter.emojiUrl}%E8%84%B8%E7%BA%A2.png">[脸红]</a>`,
        '[破涕为笑]': '😂',
        '[恐惧]': '😱',
        '[失望]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%B1%E6%9C%9B.png">[失望]</a>`,
        '[无语]': `<a href="${EmojiConverter.emojiUrl}%E6%97%A0%E8%AF%AD.png">[无语]</a>`,
        '[嘿哈]': `<a href="${EmojiConverter.emojiUrl}%E5%98%BF%E5%93%88.png">[嘿哈]</a>`,
        '[捂脸]': `<a href="${EmojiConverter.emojiUrl}%E6%8D%82%E8%84%B8.png">[捂脸]</a>`,
        '[奸笑]': `<a href="${EmojiConverter.emojiUrl}%E5%A5%B8%E7%AC%91.png">[奸笑]</a>`,
        '[机智]': `<a href="${EmojiConverter.emojiUrl}%E6%9C%BA%E6%99%BA.png">[机智]</a>`,
        '[皱眉]': `<a href="${EmojiConverter.emojiUrl}%E7%9A%B1%E7%9C%89.png">[皱眉]</a>`,
        '[耶]': `<a href="${EmojiConverter.emojiUrl}耶.png">[耶]</a>`,
        '[吃瓜]': `<a href="${EmojiConverter.emojiUrl}%E5%90%83%E7%93%9C.png">[吃瓜]</a>`,
        '[加油]': `<a href="${EmojiConverter.emojiUrl}%E5%8A%A0%E6%B2%B9.png">[加油]</a>`,
        '[汗]': `<a href="${EmojiConverter.emojiUrl}%E6%B1%97.png">[汗]</a>`,
        '[天啊]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%A9%E5%95%8A.png">[天啊]</a>`,
        '[Emm]': `<a href="${EmojiConverter.emojiUrl}Emm.png">[Emm]</a>`,
        '[社会社会]': `<a href="${EmojiConverter.emojiUrl}%E7%A4%BE%E4%BC%9A%E7%A4%BE%E4%BC%9A.png">[社会社会]</a>`,
        '[旺柴]': `<a href="${EmojiConverter.emojiUrl}%E6%97%BA%E6%9F%B4.png">[旺柴]</a>`,
        '[好的]': `<a href="${EmojiConverter.emojiUrl}%E5%A5%BD%E7%9A%84.png">[好的]</a>`,
        '[打脸]': `<a href="${EmojiConverter.emojiUrl}%E6%89%93%E8%84%B8.png">[打脸]</a>`,
        '[哇]': `<a href="${EmojiConverter.emojiUrl}%E5%93%87.png">[哇]</a>`,
        '[翻白眼]': `<a href="${EmojiConverter.emojiUrl}%E7%BF%BB%E7%99%BD%E7%9C%BC.png">[翻白眼]</a>`,
        '[666]': `<a href="${EmojiConverter.emojiUrl}666.png">[666]</a>`,
        '[让我看看]': `<a href="${EmojiConverter.emojiUrl}%E8%AE%A9%E6%88%91%E7%9C%8B%E7%9C%8B.png">[让我看看]</a>`,
        '[叹气]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%B9%E6%B0%94.png">[叹气]</a>`,
        '[苦涩]': `<a href="${EmojiConverter.emojiUrl}%E8%8B%A6%E6%B6%A9.png">[苦涩]</a>`,
        '[裂开]': `<a href="${EmojiConverter.emojiUrl}%E8%A3%82%E5%BC%80.png">[裂开]</a>`,
        '[嘴唇]': '👄',
        '[爱心]': '❤️',
        '[心碎]': '💔',
        '[拥抱]': `<a href="${EmojiConverter.emojiUrl}%E6%8B%A5%E6%8A%B1.png">[拥抱]</a>`,
        '[强]': '👍',
        '[弱]': '👎',
        '[握手]': '🤝',
        '[胜利]': '✌️',
        '[抱拳]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%B1%E6%8B%B3.png">[抱拳]</a>`,
        '[勾引]': `<a href="${EmojiConverter.emojiUrl}%E5%8B%BE%E5%BC%95.png">[勾引]</a>`,
        '[拳头]': '✊',
        '[OK]': '👌',
        '[合十]': '🙏',
        '[啤酒]': '🍺',
        '[咖啡]': '☕️',
        '[蛋糕]': '🎂',
        '[玫瑰]': '🌹',
        '[凋谢]': '🥀',
        '[菜刀]': '🔪',
        '[炸弹]': '💣',
        '[便便]': '💩',
        '[月亮]': '🌙',
        '[太阳]': '☀️',
        '[庆祝]': '🎉',
        '[礼物]': '🎁',
        '[红包]': '🧧',
        '[發]': '🀅',
        '[福]': `<a href="${EmojiConverter.emojiUrl}福.png">[福]</a>`,
        '[烟花]': `<a href="${EmojiConverter.emojiUrl}烟花.png">[烟花]</a>`,
        '[爆竹]': '🧨',
        '[猪头]': '🐷',
        '[跳跳]': `<a href="${EmojiConverter.emojiUrl}%E8%B7%B3%E8%B7%B3.png">[跳跳]</a>`,
        '[发抖]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E6%8A%96.png">[发抖]</a>`,
        '[转圈]': `<a href="${EmojiConverter.emojiUrl}%E8%BD%AC%E5%9C%88.png">[转圈]</a>`,
        // 英语表情
        '[Smile]': `<a href="${EmojiConverter.emojiUrl}%E5%BE%AE%E7%AC%91.png">[Smile]</a>`,
        '[Grimace]': `<a href="${EmojiConverter.emojiUrl}%E6%92%87%E5%98%B4.png">[撇嘴]</a>`,
        '[Drool]': '😍',
        '[Scowl]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E5%91%86.png">[发呆]</a>`,
        '[Chill]': '😎',
        '[Sob]': '😭',
        '[Shy]': `<a href="${EmojiConverter.emojiUrl}%E5%AE%B3%E7%BE%9E.png">[害羞]</a>`,
        '[Shutup]': `<a href="${EmojiConverter.emojiUrl}%E9%97%AD%E5%98%B4.png">[闭嘴]</a>`,
        '[Sleep]': '😴',
        '[Cry]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%A7%E5%93%AD.png">[大哭]</a>`,
        '[Awkward]': `<a href="${EmojiConverter.emojiUrl}%E5%B0%B4%E5%B0%AC.png">[尴尬]</a>`,
        '[Pout]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E6%80%92.png">[发怒]</a>`,
        '[Wink]': '😜',
        '[Grin]': `<a href="${EmojiConverter.emojiUrl}%E5%91%B2%E7%89%99.png">[呲牙]</a>`,
        '[Surprised]': `<a href="${EmojiConverter.emojiUrl}%E6%83%8A%E8%AE%B6.png">[惊讶]</a>`,
        '[Frown]': `<a href="${EmojiConverter.emojiUrl}%E9%9A%BE%E8%BF%87.png">[难过]</a>`,
        '[Tension]': `<a href="${EmojiConverter.emojiUrl}%E5%9B%A7.png">[囧]</a>`,
        '[Scream]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%93%E7%8B%82.png">[抓狂]</a>`,
        '[Puke]': '🤮',
        '[Chuckle]': `<a href="${EmojiConverter.emojiUrl}%E5%81%B7%E7%AC%91.png">[偷笑]</a>`,
        '[Joyful]': `<a href="${EmojiConverter.emojiUrl}%E6%84%89%E5%BF%AB.png">[愉快]</a>`,
        '[Slight]': '🙄',
        '[Smug]': `<a href="${EmojiConverter.emojiUrl}%E5%82%B2%E6%85%A2.png">[傲慢]</a>`,
        '[Drowsy]': '🥱',
        '[Panic]': `<a href="${EmojiConverter.emojiUrl}%E6%83%8A%E6%81%90.png">[惊恐]</a>`,
        '[Laugh]': `<a href="${EmojiConverter.emojiUrl}%E6%86%A8%E7%AC%91.png">[憨笑]</a>`,
        '[Loafer]': `<a href="${EmojiConverter.emojiUrl}%E6%82%A0%E9%97%B2.png">[悠闲]</a>`,
        '[Scold]': `<a href="${EmojiConverter.emojiUrl}%E5%92%92%E9%AA%82.png">[咒骂]</a>`,
        '[Doubt]': `<a href="${EmojiConverter.emojiUrl}%E7%96%91%E9%97%AE.png">[疑问]</a>`,
        '[Shhh]': `<a href="${EmojiConverter.emojiUrl}%E5%98%98.png">[嘘]</a>`,
        '[Dizzy]': '😵',
        '[BadLuck]': `<a href="${EmojiConverter.emojiUrl}%E8%A1%B0.png">[衰]</a>`,
        '[Skull]': '💀',
        '[Hammer]': `<a href="${EmojiConverter.emojiUrl}%E6%95%B2%E6%89%93.png">[敲打]</a>`,
        '[Bye]': `<a href="${EmojiConverter.emojiUrl}%E5%86%8D%E8%A7%81.png">[再见]</a>`,
        '[Relief]': `<a href="${EmojiConverter.emojiUrl}%E6%93%A6%E6%B1%97.png">[擦汗]</a>`,
        '[DigNose]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%A0%E9%BC%BB.png">[抠鼻]</a>`,
        '[Clap]': `<a href="${EmojiConverter.emojiUrl}%E9%BC%93%E6%8E%8C.png">[鼓掌]</a>`,
        '[Trick]': `<a href="${EmojiConverter.emojiUrl}%E5%9D%8F%E7%AC%91.png">[坏笑]</a>`,
        '[Bah！R]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%B3%E5%93%BC%E5%93%BC.png">[右哼哼]</a>`,
        '[Lookdown]': `<a href="${EmojiConverter.emojiUrl}%E9%84%99%E8%A7%86.png">[鄙视]</a>`,
        '[Wronged]': `<a href="${EmojiConverter.emojiUrl}%E5%A7%94%E5%B1%88.png">[委屈]</a>`,
        '[Puling]': `<a href="${EmojiConverter.emojiUrl}%E5%BF%AB%E5%93%AD%E4%BA%86.png">[快哭了]</a>`,
        '[Sly]': `<a href="${EmojiConverter.emojiUrl}%E9%98%B4%E9%99%A9.png">[阴险]</a>`,
        '[Kiss]': `<a href="${EmojiConverter.emojiUrl}%E4%BA%B2%E4%BA%B2.png">[亲亲]</a>`,
        '[Whimper]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%AF%E6%80%9C.png">[可怜]</a>`,
        '[Happy]': `<a href="${EmojiConverter.emojiUrl}%E7%AC%91%E8%84%B8.png">[笑脸]</a>`,
        '[Sick]': `<a href="${EmojiConverter.emojiUrl}%E7%94%9F%E7%97%85.png">[生病]</a>`,
        '[Flushed]': `<a href="${EmojiConverter.emojiUrl}%E8%84%B8%E7%BA%A2.png">[脸红]</a>`,
        '[Lol]': '😂',
        '[Terror]': '😱',
        '[Let Down]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%B1%E6%9C%9B.png">[失望]</a>`,
        '[Duh]': `<a href="${EmojiConverter.emojiUrl}%E6%97%A0%E8%AF%AD.png">[无语]</a>`,
        '[Hey]': `<a href="${EmojiConverter.emojiUrl}%E5%98%BF%E5%93%88.png">[嘿哈]</a>`,
        '[Facepalm]': `<a href="${EmojiConverter.emojiUrl}%E6%8D%82%E8%84%B8.png">[捂脸]</a>`,
        '[Smirk]': `<a href="${EmojiConverter.emojiUrl}%E5%A5%B8%E7%AC%91.png">[奸笑]</a>`,
        '[Smart]': `<a href="${EmojiConverter.emojiUrl}%E6%9C%BA%E6%99%BA.png">[机智]</a>`,
        '[Concerned]': `<a href="${EmojiConverter.emojiUrl}%E7%9A%B1%E7%9C%89.png">[皱眉]</a>`,
        '[Yeah!]': `<a href="${EmojiConverter.emojiUrl}耶.png">[Yeah!]</a>`,
        '[Onlooker]': `<a href="${EmojiConverter.emojiUrl}%E5%90%83%E7%93%9C.png">[吃瓜]</a>`,
        '[GoForIt]': `<a href="${EmojiConverter.emojiUrl}%E5%8A%A0%E6%B2%B9.png">[加油]</a>`,
        '[Sweats]': `<a href="${EmojiConverter.emojiUrl}%E6%B1%97.png">[汗]</a>`,
        '[OMG]': `<a href="${EmojiConverter.emojiUrl}%E5%A4%A9%E5%95%8A.png">[天啊]</a>`,
        // '[Emm]': `<a href="${EmojiConverter.emojiUrl}Emm.png">[Emm]</a>`,
        '[Respect]': `<a href="${EmojiConverter.emojiUrl}%E7%A4%BE%E4%BC%9A%E7%A4%BE%E4%BC%9A.png">[社会社会]</a>`,
        '[Doge]': `<a href="${EmojiConverter.emojiUrl}%E6%97%BA%E6%9F%B4.png">[旺柴]</a>`,
        '[NoProb]': `<a href="${EmojiConverter.emojiUrl}%E5%A5%BD%E7%9A%84.png">[好的]</a>`,
        '[MyBad]': `<a href="${EmojiConverter.emojiUrl}%E6%89%93%E8%84%B8.png">[打脸]</a>`,
        '[Wow]': `<a href="${EmojiConverter.emojiUrl}%E5%93%87.png">[哇]</a>`,
        '[Boring]': `<a href="${EmojiConverter.emojiUrl}%E7%BF%BB%E7%99%BD%E7%9C%BC.png">[翻白眼]</a>`,
        '[Awesome]': `<a href="${EmojiConverter.emojiUrl}666.png">[666]</a>`,
        '[LetMeSee]': `<a href="${EmojiConverter.emojiUrl}%E8%AE%A9%E6%88%91%E7%9C%8B%E7%9C%8B.png">[让我看看]</a>`,
        '[Sigh]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%B9%E6%B0%94.png">[叹气]</a>`,
        '[Hurt]': `<a href="${EmojiConverter.emojiUrl}%E8%8B%A6%E6%B6%A9.png">[苦涩]</a>`,
        '[Broken]': `<a href="${EmojiConverter.emojiUrl}%E8%A3%82%E5%BC%80.png">[裂开]</a>`,
        '[Lip]': '👄',
        '[Heart]': '❤️',
        '[BrokenHeart]': '💔',
        '[Hug]': `<a href="${EmojiConverter.emojiUrl}%E6%8B%A5%E6%8A%B1.png">[拥抱]</a>`,
        '[Strong]': '👍',
        '[Weak]': '👎',
        '[Shake]': '🤝',
        '[Victory]': '✌️',
        '[Salute]': `<a href="${EmojiConverter.emojiUrl}%E6%8A%B1%E6%8B%B3.png">[抱拳]</a>`,
        '[Beckon]': `<a href="${EmojiConverter.emojiUrl}%E5%8B%BE%E5%BC%95.png">[勾引]</a>`,
        '[Fist]': '✊',
        // '[OK]': `<a href="${EmojiConverter.emojiUrl}OK.png">[OK]</a>`,
        '[Worship]': '🙏',
        '[Beer]': '🍺',
        '[Coffee]': '☕️',
        '[Cake]': '🎂',
        '[Rose]': '🌹',
        '[Wilt]': '🥀',
        '[Cleaver]': '🔪',
        '[Bomb]': '💣',
        '[Poop]': '💩',
        '[Moon]': '🌙',
        '[Sun]': '☀️',
        '[Party]': '🎉',
        '[Gift]': '🎁',
        '[Packet]': '🧧',
        '[Rich]': '🀅',
        '[Blessing]': `<a href="${EmojiConverter.emojiUrl}福.png">[福]</a>`,
        '[Fireworks]': `<a href="${EmojiConverter.emojiUrl}烟花.png">[烟花]</a>`,
        '[Firecracker]': '🧨',
        '[Pig]': '🐷',
        '[Waddle]': `<a href="${EmojiConverter.emojiUrl}%E8%B7%B3%E8%B7%B3.png">[Waddle]</a>`,
        '[Tremble]': `<a href="${EmojiConverter.emojiUrl}%E5%8F%91%E6%8A%96.png">[Tremble]</a>`,
        '[Twirl]': `<a href="${EmojiConverter.emojiUrl}%E8%BD%AC%E5%9C%88.png">[Twirl]</a>`
    }

    // TODO: tg://addstickers?set=WeChatPack use this one when Premium user
    public emojiMappingPremium: Record<string, string> = {}
    public weChatToTelegramEmojiMapping: Record<string, string> = {
        '[微笑]': '🙂',
        '[撇嘴]': '😟',
        '[色]': '😍',
        '[发呆]': '😶',
        '[得意]': '😎',
        '[流泪]': '😭',
        '[害羞]': '😳',
        '[闭嘴]': '🤐',
        '[睡]': '😴',
        '[大哭]': '😢',
        '[尴尬]': '😬',
        '[发怒]': '😡',
        '[调皮]': '😜',
        '[呲牙]': '😁',
        '[惊讶]': '😮',
        '[难过]': '😟',
        '[囧]': '😖',
        '[抓狂]': '😫',
        '[吐]': '🤮',
        '[偷笑]': '😆',
        '[愉快]': '😄',
        '[白眼]': '🙄',
        '[傲慢]': '😕',
        '[困]': '🥱',
        '[惊恐]': '😱',
        '[憨笑]': '😄',
        '[悠闲]': '😏',
        '[咒骂]': '😠',
        '[疑问]': '🤔',
        '[嘘]': '🤫',
        '[晕]': '😵',
        '[衰]': '😞',
        '[骷髅]': '💀',
        '[敲打]': '👊',
        '[再见]': '👋',
        '[擦汗]': '😓',
        '[抠鼻]': '👃',
        '[鼓掌]': '👏',
        '[坏笑]': '😈',
        '[右哼哼]': '😤',
        '[鄙视]': '😒',
        '[委屈]': '😿',
        '[快哭了]': '😭',
        '[阴险]': '😏',
        '[亲亲]': '😚',
        '[可怜]': '🥺',
        '[笑脸]': '😄',
        '[生病]': '🤒',
        '[脸红]': '😊',
        '[破涕为笑]': '😂',
        '[恐惧]': '😨',
        '[失望]': '😞',
        '[无语]': '😶',
        '[嘿哈]': '😄',
        '[捂脸]': '🤦',
        '[奸笑]': '😼',
        '[机智]': '🧠',
        '[皱眉]': '😟',
        '[耶]': '✌️',
        '[吃瓜]': '🍉',
        '[加油]': '💪',
        '[汗]': '😅',
        '[天啊]': '🤯',
        '[Emm]': '🤔',
        '[社会社会]': '🤝',
        '[旺柴]': '🐶',
        '[好的]': '👌',
        '[打脸]': '🤕',
        '[哇]': '😮',
        '[翻白眼]': '🙄',
        '[666]': '👌',
        '[让我看看]': '👀',
        '[叹气]': '😔',
        '[苦涩]': '😖',
        '[裂开]': '😲',
        '[嘴唇]': '👄',
        '[爱心]': '❤️',
        '[心碎]': '💔',
        '[拥抱]': '🤗',
        '[强]': '👍',
        '[弱]': '👎',
        '[握手]': '🤝',
        '[胜利]': '✌️',
        '[抱拳]': '🙏',
        '[勾引]': '😉',
        '[拳头]': '✊',
        '[OK]': '👌',
        '[合十]': '🙏',
        '[啤酒]': '🍺',
        '[咖啡]': '☕️',
        '[蛋糕]': '🍰',
        '[玫瑰]': '🌹',
        '[凋谢]': '🥀',
        '[菜刀]': '🔪',
        '[炸弹]': '💣',
        '[便便]': '💩',
        '[月亮]': '🌜',
        '[太阳]': '☀️',
        '[庆祝]': '🎉',
        '[礼物]': '🎁',
        '[红包]': '🧧',
        '[发]': '💸',
        '[福]': '🧧',
        '[烟花]': '🎆',
        '[爆竹]': '🧨',
        '[猪头]': '🐷',
        '[跳跳]': '🦘',
        '[发抖]': '🥶',
        '[转圈]': '🌀',
        '[Smile]': '🙂',
        '[Grimace]': '😟',
        '[Drool]': '😍',
        '[Scowl]': '😶',
        '[Chill]': '😎',
        '[Sob]': '😭',
        '[Shy]': '😳',
        '[Shutup]': '🤐',
        '[Sleep]': '😴',
        '[Cry]': '😢',
        '[Awkward]': '😬',
        '[Pout]': '😡',
        '[Wink]': '😜',
        '[Grin]': '😁',
        '[Surprised]': '😮',
        '[Frown]': '😟',
        '[Tension]': '😖',
        '[Scream]': '😫',
        '[Puke]': '🤮',
        '[Chuckle]': '😆',
        '[Joyful]': '😄',
        '[Slight]': '🙄',
        '[Smug]': '😕',
        '[Drowsy]': '🥱',
        '[Panic]': '😱',
        '[Laugh]': '😄',
        '[Loafer]': '😏',
        '[Scold]': '😠',
        '[Doubt]': '🤔',
        '[Shhh]': '🤫',
        '[Dizzy]': '😵',
        '[BadLuck]': '😞',
        '[Skull]': '💀',
        '[Hammer]': '👊',
        '[Bye]': '👋',
        '[Relief]': '😓',
        '[DigNose]': '👃',
        '[Clap]': '👏',
        '[Trick]': '😈',
        '[Bah！R]': '😤',
        '[Lookdown]': '😒',
        '[Wronged]': '😿',
        '[Puling]': '😭',
        '[Sly]': '😏',
        '[Kiss]': '😚',
        '[Whimper]': '🥺',
        '[Happy]': '😄',
        '[Sick]': '🤒',
        '[Flushed]': '😊',
        '[Lol]': '😂',
        '[Terror]': '😨',
        '[Let Down]': '😞',
        '[Duh]': '😶',
        '[Hey]': '😄',
        '[Facepalm]': '🤦',
        '[Smirk]': '😼',
        '[Smart]': '🧠',
        '[Concerned]': '😟',
        '[Yeah!]': '✌️',
        '[Onlooker]': '🍉',
        '[GoForIt]': '💪',
        '[Sweats]': '😅',
        '[OMG]': '🤯',
        '[Respect]': '🤝',
        '[Doge]': '🐶',
        '[NoProb]': '👌',
        '[MyBad]': '🤕',
        '[Wow]': '😮',
        '[Boring]': '🙄',
        '[Awesome]': '👌',
        '[LetMeSee]': '👀',
        '[Sigh]': '😔',
        '[Hurt]': '😖',
        '[Broken]': '😲',
        '[Lip]': '👄',
        '[Heart]': '❤️',
        '[BrokenHeart]': '💔',
        '[Hug]': '🤗',
        '[Strong]': '👍',
        '[Weak]': '👎',
        '[Shake]': '🤝',
        '[Victory]': '✌️',
        '[Salute]': '🙏',
        '[Beckon]': '😉',
        '[Fist]': '✊',
        // '[OK]': '👌',
        '[Worship]': '🙏',
        '[Beer]': '🍺',
        '[Coffee]': '☕️',
        '[Cake]': '🍰',
        '[Rose]': '🌹',
        '[Wilt]': '🥀',
        '[Cleaver]': '🔪',
        '[Bomb]': '💣',
        '[Poop]': '💩',
        '[Moon]': '🌜',
        '[Sun]': '☀️',
        '[Party]': '🎉',
        '[Gift]': '🎁',
        '[Packet]': '🧧',
        '[Rich]': '💸',
        '[Blessing]': '🧧',
        '[Fireworks]': '🎆',
        '[Firecracker]': '🧨',
        '[Pig]': '🐷',
        '[Waddle]': '🦘',
        '[Tremble]': '🥶',
        '[Twirl]': '🌀',
    }

    convert(text: string, config: Configuration) {
        let convertedText = text
        let mapping = this.emojiMapping
        if (config.emojiPicture) {
            mapping = this.emojiMapping
        } else {
            mapping = {}
        }
        for (const emojiText in mapping) {
            if (Object.prototype.hasOwnProperty.call(mapping, emojiText)) {
                const emojiUnicode = mapping[emojiText]
                const emojiRegex = new RegExp(emojiText.replace('[', '\\[').replace(']', '\\]'), 'g')
                convertedText = convertedText.replace(emojiRegex, emojiUnicode)
            }
        }
        return convertedText
    }
}